version: '3.1'
services:
  springboot:
    image: roopakasireddy/dockerimage-compose-file:TAG
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
